from django.db import models

class Master(models.Model):
    player_code = models.CharField(max_length=20, blank=True)
    birth_year = models.IntegerField(null=True)
    birth_month = models.IntegerField(null=True)
    birth_day = models.IntegerField(null=True)
    birth_country = models.CharField(max_length=50, blank=True)
    birth_state = models.CharField(max_length=50, blank=True)
    birth_city = models.CharField(max_length=50, blank=True)
    death_year = models.IntegerField(null=True)
    death_month = models.IntegerField(null=True)
    death_day = models.IntegerField(null=True)
    death_country = models.CharField(max_length=50, blank=True)
    death_state = models.CharField(max_length=50, blank=True)
    death_city = models.CharField(max_length=50, blank=True)
    name_first = models.CharField(max_length=20, blank=True)
    name_last = models.CharField(max_length=20, blank=True)
    name_given = models.CharField(max_length=50, blank=True)
    weight = models.IntegerField(null=True)
    height = models.IntegerField(null=True)
    bats = models.CharField(max_length=1, blank=True)
    throws = models.CharField(max_length=1, blank=True)
    debut = models.CharField(max_length=20, blank=True)
    final_game = models.CharField(max_length=20, blank=True)
    retro_code = models.CharField(max_length=20, blank=True)
    bbref_code = models.CharField(max_length=20, blank=True)


class Batting(models.Model):
    player_code = models.ForeignKey(Master)
    year_code = models.IntegerField(null=True)
    stint = models.IntegerField(null=True)
    team_code = models.CharField(max_length=10, blank=True)
    league_code = models.CharField(max_length=10, blank=True)
    games = models.IntegerField(null=True)
    at_bats = models.IntegerField(null=True)
    runs = models.IntegerField(null=True)
    hits = models.IntegerField(null=True)
    doubles = models.IntegerField(null=True)
    triples = models.IntegerField(null=True)
    homeruns = models.IntegerField(null=True)
    runs_batted_in = models.IntegerField(null=True)
    stolen_bases = models.IntegerField(null=True)
    caught_stealing = models.IntegerField(null=True)
    base_on_balls = models.IntegerField(null=True)
    strikeouts = models.IntegerField(null=True)
    intentional_walks = models.IntegerField(null=True)
    hit_by_pitch = models.IntegerField(null=True)
    sacrifice_hits = models.IntegerField(null=True)
    sacrifice_flies = models.IntegerField(null=True)
    grounded_into_double_plays = models.IntegerField(null=True)
    
