# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_code', models.CharField(blank=True, max_length=20)),
                ('birth_year', models.IntegerField(null=True)),
                ('birth_month', models.IntegerField(null=True)),
                ('birth_day', models.IntegerField(null=True)),
                ('birth_country', models.CharField(blank=True, max_length=50)),
                ('birth_state', models.CharField(blank=True, max_length=50)),
                ('birth_city', models.CharField(blank=True, max_length=50)),
                ('death_year', models.IntegerField(null=True)),
                ('death_month', models.IntegerField(null=True)),
                ('death_day', models.IntegerField(null=True)),
                ('death_country', models.CharField(blank=True, max_length=50)),
                ('death_state', models.CharField(blank=True, max_length=50)),
                ('death_city', models.CharField(blank=True, max_length=50)),
                ('name_first', models.CharField(blank=True, max_length=20)),
                ('name_last', models.CharField(blank=True, max_length=20)),
                ('name_given', models.CharField(blank=True, max_length=50)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('bats', models.CharField(blank=True, max_length=1)),
                ('throws', models.CharField(blank=True, max_length=1)),
                ('debut', models.CharField(blank=True, max_length=20)),
                ('final_game', models.CharField(blank=True, max_length=20)),
                ('retro_code', models.CharField(blank=True, max_length=20)),
                ('bbref_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
