# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.IntegerField(null=True)),
                ('stint', models.IntegerField(null=True)),
                ('team_code', models.CharField(blank=True, max_length=10)),
                ('league_code', models.CharField(blank=True, max_length=10)),
                ('games', models.IntegerField(null=True)),
                ('at_bats', models.IntegerField(null=True)),
                ('runs', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('doubles', models.IntegerField(null=True)),
                ('triples', models.IntegerField(null=True)),
                ('homeruns', models.IntegerField(null=True)),
                ('runs_batted_in', models.IntegerField(null=True)),
                ('stolen_bases', models.IntegerField(null=True)),
                ('caught_stealing', models.IntegerField(null=True)),
                ('base_on_balls', models.IntegerField(null=True)),
                ('strikeouts', models.IntegerField(null=True)),
                ('intentional_walks', models.IntegerField(null=True)),
                ('hit_by_pitch', models.IntegerField(null=True)),
                ('sacrifice_hits', models.IntegerField(null=True)),
                ('sacrifice_flies', models.IntegerField(null=True)),
                ('grounded_into_double_plays', models.IntegerField(null=True)),
                ('player_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_api_app.Master')),
            ],
        ),
    ]
