# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_api_app', '0003_auto_20161026_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_code', models.IntegerField(null=True)),
                ('stint', models.IntegerField(null=True)),
                ('team_code', models.CharField(blank=True, max_length=10)),
                ('league_code', models.CharField(blank=True, max_length=10)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('games', models.IntegerField(null=True)),
                ('games_started', models.IntegerField(null=True)),
                ('inn_outs', models.FloatField(null=True)),
                ('putouts', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('errors', models.IntegerField(null=True)),
                ('double_plays', models.IntegerField(null=True)),
                ('passed_balls', models.IntegerField(null=True)),
                ('wild_pitches', models.IntegerField(null=True)),
                ('opp_stolen_bases', models.IntegerField(null=True)),
                ('opp_caught_stealing', models.IntegerField(null=True)),
                ('zone_rating', models.FloatField(null=True)),
                ('player_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball_api_app.Master')),
            ],
        ),
        migrations.AlterField(
            model_name='pitching',
            name='earned_run_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='opponent_batting_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='outs_pitched',
            field=models.FloatField(null=True),
        ),
    ]
