# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:21
from __future__ import unicode_literals

from django.db import migrations

import csv

def add_info(apps, schema_editor):
    Master = apps.get_model("baseball_api_app", "Master")
    Batting = apps.get_model("baseball_api_app", "Batting")
    Pitching = apps.get_model("baseball_api_app", "Pitching")
    Fielding = apps.get_model("baseball_api_app", "Fielding")

    with open("master.csv") as open_file:
        master_info = csv.DictReader(open_file)
        for row in master_info:
            Master.objects.create(player_code=row["playerID"],birth_year=row["birthYear"],birth_month=row["birthMonth"],birth_day=row["birthDay"],
                                  birth_country=row["birthCountry"],birth_state=row["birthState"],birth_city=row["birthCity"],death_year=row["deathYear"],
                                  death_month=row["deathMonth"],death_day=row["deathDay"],death_country=row["deathCountry"],death_state=row["deathState"],
                                  death_city=row["deathCity"],name_first=row["nameFirst"],name_last=row["nameLast"],name_given=row["nameGiven"],
                                  weight=row["weight"],height=row["height"],bats=row["bats"],throws=row["throws"],
                                  debut=row["debut"],final_game=row["finalGame"],retro_code=row["retroID"],bbref_code=row["bbrefID"]
                                  )


    with open("batting.csv") as open_file:
        batting_info = csv.DictReader(open_file)
        for row in batting_info:
            player_code = Master.objects.get(player_code=row["playerID"])
            Batting.objects.create(player_code=player_code,year_code=row["yearID"],stint=row["stint"],team_code=row["teamID"],
                                   league_code=row["lgID"],games=row["G"],at_bats=row["AB"],runs=row["R"],hits=row["H"],
                                   doubles=row["2B"],triples=row["3B"],runs_batted_in=row["RBI"],stolen_bases=row["SB"],
                                   caught_stealing=row["CS"],walks=row["BB"],strikeouts=row["SO"],intentional_walks=row["IBB"],
                                   hit_by_pitch=row["HBP"],sacrifice_hits=row["SH"],sacrifice_flies=row["SF"],grounded_into_double_plays=row["GIDP"]
                                   )

    raise Exception ("OOGLY BOOGLY")





class Migration(migrations.Migration):

    dependencies = [
        ('baseball_api_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_info)
    ]
