# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:47
from __future__ import unicode_literals

from django.db import migrations

import csv

def add_info(apps, schema_editor):
    Master = apps.get_model("baseball_api_app", "Master")
    Batting = apps.get_model("baseball_api_app", "Batting")
    Pitching = apps.get_model("baseball_api_app", "Pitching")
    Fielding = apps.get_model("baseball_api_app", "Fielding")

    with open("batting.csv") as open_file:
        batting_info = csv.DictReader(open_file)
        for row in batting_info:
            player_code = Master.objects.get(player_code=row["playerID"])
            Batting.objects.create(player_code=player_code,year_code=row["yearID"],stint=row["stint"],team_code=row["teamID"],
                                   league_code=row["lgID"],games=row["G"],at_bats=row["AB"],runs=row["R"],hits=row["H"],
                                   doubles=row["2B"],triples=row["3B"],runs_batted_in=row["RBI"],stolen_bases=row["SB"],
                                   caught_stealing=row["CS"],walks=row["BB"],strikeouts=row["SO"],intentional_walks=row["IBB"],
                                   hit_by_pitch=row["HBP"],sacrifice_hits=row["SH"],sacrifice_flies=row["SF"],grounded_into_double_plays=row["GIDP"]
                                   )

class Migration(migrations.Migration):

    dependencies = [
        ('baseball_api_app', '0005_auto_20161026_2021'),
    ]

    operations = [
        migrations.RunPython(add_info)
    ]
