# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 00:44
from __future__ import unicode_literals

from django.db import migrations

import csv


def add_info(apps, schema_editor):
    Master = apps.get_model("baseball_api_app", "Master")
    Batting = apps.get_model("baseball_api_app", "Batting")
    Pitching = apps.get_model("baseball_api_app", "Pitching")
    Fielding = apps.get_model("baseball_api_app", "Fielding")

    with open("pitching.csv") as open_file:
        pitching_info = csv.DictReader(open_file)
        for row in pitching_info:
            player_code = Master.objects.get(player_code=row["playerID"])
            Pitching.objects.create(player_code=player_code,year_code=row["yearID"],stint=row["stint"],team_code=row["teamID"],
                                   league_code=row["lgID"],wins=row["W"],losses=row["L"],games=row["G"],games_started=row["GS"],
                                   completed_games=row["CG"],shutouts=row["SHO"],saves=row["SV"],outs_pitched=row["IPouts"],
                                   hits=row["H"],earned_runs=row["ER"],homeruns=row["HR"],walks=row["BB"],strikeouts=row["SO"],
                                   opponent_batting_average=row["BAOpp"],earned_run_average=row["ERA"],intentional_walks=row["IBB"],wild_pitches=row["WP"],
                                   batters_hit_by_pitch=row["HBP"],balks=row["BK"],batters_faced_by_pitcher=row["BFP"],games_finished=row["GF"],
                                   runs_allowed=row["R"],sacrifices_by_opp_batters=row["SH"],sacrifice_flies_by_opp_batters=row["SF"],grounded_into_double_plays_by_opp_batters=row["GIDP"],
                                   )
    raise Exception ("OOGLY BOOGLY")


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_api_app', '0006_auto_20161026_2347'),
    ]

    operations = [
            migrations.RunPython(add_info)
    ]
